#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP -d I
bspc monitor DisplayPort-1 -d I

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
